-- MySQL Script generated by MySQL Workbench
-- Wed Jul  8 22:33:29 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema weibo
-- -----------------------------------------------------
-- 微博库
DROP SCHEMA IF EXISTS `weibo` ;

-- -----------------------------------------------------
-- Schema weibo
--
-- 微博库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weibo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `weibo` ;

-- -----------------------------------------------------
-- Table `weibo`.`hd_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_user` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `account` VARCHAR(45) NOT NULL COMMENT '',
  `password` CHAR(32) NOT NULL COMMENT '',
  `registtime` INT(10) UNSIGNED NULL COMMENT '',
  `lock` TINYINT(1) UNSIGNED NOT NULL COMMENT '是否锁定1标示锁定\n0标示未锁定',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `account` (`account` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `weibo`.`hd_userinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_userinfo` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_userinfo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `truename` VARCHAR(45) NULL COMMENT '',
  `sex` ENUM('男', '女') NULL DEFAULT '男' COMMENT '',
  `location` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '',
  `constellation` CHAR(10) NOT NULL DEFAULT '' COMMENT '',
  `intro` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '',
  `face50` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '',
  `face80` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '',
  `face180` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '',
  `style` VARCHAR(45) NOT NULL DEFAULT 'default' COMMENT '',
  `follow` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `fans` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `weibo` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_userinfo_hd_user`
    FOREIGN KEY (`uid`)
    REFERENCES `weibo`.`hd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_group` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_group` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_group_hd_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `weibo`.`hd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_follow` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_follow` (
  `fllow` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `fans` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `gid` INT NOT NULL COMMENT '',
  INDEX `fllows` (`fllow` ASC)  COMMENT '',
  INDEX `fans` (`fans` ASC)  COMMENT '',
  INDEX `gid` (`gid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_follow_hd_group1`
    FOREIGN KEY (`gid`)
    REFERENCES `weibo`.`hd_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_letter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_letter` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_letter` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `from` INT NOT NULL COMMENT '发信用户ID',
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_letter_hd_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `weibo`.`hd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_weibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_weibo` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_weibo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '',
  `istrun` INT NOT NULL DEFAULT 0 COMMENT '是否是转发，如果是原发为0 ，如果转发，为转发微博的ID',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '',
  `turn` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `keep` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `comment` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_weibo_hd_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `weibo`.`hd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_picture` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_picture` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `mini` VARCHAR(60) NOT NULL COMMENT '',
  `medium` VARCHAR(60) NOT NULL COMMENT '',
  `max` VARCHAR(60) NOT NULL COMMENT '',
  `wid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `wid` (`wid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_picture_hd_weibo1`
    FOREIGN KEY (`wid`)
    REFERENCES `weibo`.`hd_weibo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_comment` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_comment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `content` VARCHAR(45) NOT NULL COMMENT '',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  `wid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  INDEX `wid` (`wid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_comment_hd_weibo1`
    FOREIGN KEY (`wid`)
    REFERENCES `weibo`.`hd_weibo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_keep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_keep` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_keep` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `uid` INT NOT NULL COMMENT '收藏用户的ID\n',
  `time` INT UNSIGNED NOT NULL COMMENT '收藏时间',
  `wid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `wid` (`wid` ASC)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_keep_hd_weibo1`
    FOREIGN KEY (`wid`)
    REFERENCES `weibo`.`hd_weibo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weibo`.`hd_atme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weibo`.`hd_atme` ;

CREATE TABLE IF NOT EXISTS `weibo`.`hd_atme` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `wid` INT NOT NULL COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  INDEX `wid` (`wid` ASC)  COMMENT '',
  CONSTRAINT `fk_hd_atme_hd_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `weibo`.`hd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
